version: '3.8'
services:
  csv-process-app:
    container_name: csv-process-app
    build:
      context: . # Assumes Dockerfile is in the same directory
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Nginx default)
    restart: unless-stopped
    networks:
      - caddy_net # Ensure this is the network Caddy uses
networks:
  caddy_net: # Ensure this is the network Caddy uses
    external: true